### ISSUE TITLE
Cerificate expired. 

### ISSUE THREAD

**Issue by MustansirZia** [stathat/consistent#18]
Hi! I got this error when I tried to go get. Would you mind taking a look? 

```go get stathat.com/c/consistent
package stathat.com/c/consistent: unrecognised import path "stathat.com/c/consistent" (https fetch: Get https://stathat.com/c/consistent?go-get=1: x509: certificate has expired or is not yet valid)```

**Comment by patrickxb** [comment]
Sorry, this should be fixed now.

**Comment by MustansirZia** [comment]
Yes. Thank You!

**Comment by hackerwins** [comment]
Thanks for your work. I got the same error now. Would you mind taking a look?
<img width="911" alt="Screen Shot 2019-10-15 at 12 38 08 PM" src="https://user-images.githubusercontent.com/2059311/66798420-e3338900-ef48-11e9-919f-c638dda9283a.png">
