### ISSUE TITLE
go get faild

### ISSUE THREAD

**Issue by Disac** [stathat/consistent#21]
Get https://stathat.com/c/consistent?go-get=1: x509: certificate has expired or is not yet valid

**Comment by patrickxb** [comment]
Sorry, can you try again?

**Comment by andy256** [comment]
The HTTPS certificate on stathat.com expired again, 9 days ago.

```
package stathat.com/c/consistent: unrecognized import path "stathat.com/c/consistent" (https fetch: Get https://stathat.com/c/consistent?go-get=1: x509: certificate has expired or is not yet valid)
```

**Comment by patrickxb** [comment]
Fixed

**Comment by andy256** [comment]
Thank you!

**Comment by wozaki** [comment]
Expired again.
Would you please fix it? 🙇 

```
$ openssl s_client -connect stathat.com:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Jun 25 02:44:40 2018 GMT
notAfter=Sep 23 02:44:40 2018 GMT
```

**Comment by digitalysin** [comment]
doesn't work again, please fix the issue

**Comment by sendya** [comment]
![sp20190104-222832](https://user-images.githubusercontent.com/5404542/50692848-34d0ee00-1070-11e9-818f-2c23d414c39c.png)

04/01/2019   doesn't work again
