### ISSUE TITLE
https certificate has expired today,

### ISSUE THREAD

**Issue by songouku** [stathat/consistent#24]
Hello, your https certificate has expired today, the package is no longer available, can you fix it?

**Comment by donychen1134** [comment]
https fetch: Get https://www.stathat.com/c/consistent?go-get=1: x509: certificate has expired or is not yet valid

----------------------------
I have the same problem. 
Please fix it. 
Thank you.

**Comment by songouku** [comment]
@donychen1134   replace   stathat.com/c/consistent => github.com/stathat/consistent latest

**Comment by patrickxb** [comment]
it's fixed
