### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by pkieltyka** [stathat/consistent#9]
$ go get -v -d stathat.com/c/consistent
Fetching https://stathat.com/c/consistent?go-get=1
https fetch failed.
import "stathat.com/c/consistent": https fetch: Get https://stathat.com/c/consistent?go-get=1: dial tcp 50.17.204.11:443: getsockopt: connection refused
package stathat.com/c/consistent: unrecognized import path "stathat.com/c/consistent"

**Comment by patrickxb** [comment]
Just tried it and it worked fine.  Are you still having an issue?

**Comment by pkieltyka** [comment]
yes it still fails.

**Comment by patrickxb** [comment]
There seems to be something wrong with https, but falling back to http works for me.  Will look into https issue later, not able to right now:

    $ go get -v -d stathat.com/c/consistent
    Fetching https://stathat.com/c/consistent?go-get=1
    https fetch failed.
    Fetching http://stathat.com/c/consistent?go-get=1
    Parsing meta tags from http://stathat.com/c/consistent?go-get=1 (status code 200)
    get "stathat.com/c/consistent": found meta tag main.metaImport{Prefix:"stathat.com/c/consistent", VCS:"git", RepoRoot:"https://github.com/stathat/consistent"} at http://stathat.com/c/consistent?go-get=1
    stathat.com/c/consistent (download)

**Comment by patrickxb** [comment]
Ok, can you try again?

**Comment by rwynn** [comment]
I am also seeing this problem today.

$ go version
```
go version go1.6.2 linux/amd64`
```

$ go get -v -d stathat.com/c/consistent
```
Fetching https://stathat.com/c/consistent?go-get=1
https fetch failed: Get https://stathat.com/c/consistent?go-get=1: dial tcp 54.231.1.172:443: getsockopt: connection refused
package stathat.com/c/consistent: unrecognized import path "stathat.com/c/consistent" (https fetch: Get https://stathat.com/c/consistent?go-get=1: dial tcp 54.231.1.172:443: getsockopt: connection refused)
```
